title: Marina Lovchikova, PhD
position: Senior Researcher
affiliation: Covered California
email: marina.lovchikova@gmail.com
keywords: marina lovchikova
google_scholar: 
github_link: 
linkedin: https://www.linkedin.com/in/mlovchikova
avatar: ./assets/headshot.jpg
google_analytics: 
favicon: 
favicon_dark: 
description: 
canonical: mlovchikova.github.io
remote_theme: yaoyao-liu/minimal-light
