title: Marina Lovchikova
position: Ph.D. Candidate
affiliation: University of California, Davis
email: mlovchikova (at) ucdavis.edu
keywords: marina lovchikova
google_scholar: 
github_link: https://github.com/mlovchikova
linkedin: https://www.linkedin.com/in/mlovchikova
avatar: ./assets/headshot.jpg
google_analytics: 
favicon: 
favicon_dark: 
description: 
canonical: mlovchikova.github.io
remote_theme: yaoyao-liu/minimal-light
